### ISSUE TITLE
NRE from RegisterReminderAsync()

### ISSUE THREAD

**Issue by sandersaares** [loekd/ServiceFabric.Mocks#2]
I have an actor that is being tested via a mocked ActorService. When it tries to register a reminder, it encounters a NullReferenceException coming (based on stack trace information) from within the stateful storage system.

```
System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
           at Microsoft.ServiceFabric.Actors.Runtime.KvsActorStateProvider.<AddOrUpdateReminderAsync>d__4c.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at Microsoft.ServiceFabric.Actors.Runtime.ActorStateProviderHelper.<>c__DisplayClass1.<<ExecuteWithRetriesAsync>b__0>d__3.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at Microsoft.ServiceFabric.Actors.Runtime.ActorStateProviderHelper.<ExecuteWithRetriesAsync>d__6`1.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at Microsoft.ServiceFabric.Actors.Runtime.MockActorManager.<RegisterOrUpdateReminderAsync>d__5.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at Microsoft.ServiceFabric.Actors.Runtime.ActorBase.<RegisterReminderAsync>d__3.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
        FileThingy\FileThingy.cs(109,0): at FileThingy.FileThingy.<TakeLeaseAsync>d__13.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        Tests\FileThingyTests.cs(51,0): at Tests.FileThingyTests.<TakeLease_TwiceInARow_RemembersLongestLease>d__3.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Using SF SDK 2.3.301 and ServiceFabric.Mocks 0.9.4.

This is the call that fails:

```
await RegisterReminderAsync(CleanupReminderName, null, durationFromNow, CleanupRetryInterval);
```

There is no actor state saved before this reminder registration call.

**Comment by sandersaares** [comment]
Poking deeper, `KvsActorStateProvider.storeReplica` appears to be null, which is why `KvsActorStateProvider` is crashing with a NRE. The internal logic and structure there is mostly beyond my understanding but this field appears to be initialized by the `IStateProviderReplica.Initialize()` implementation, which is apparently never called.

**Comment by loekd** [comment]
Thanks for taking the time to investigate and provide feedback. I'll investigate too, and report back. Probably, introducing a MockActorStateProvider will do the trick for this. 
(I'll also take pull requests if you have them.)

**Comment by loekd** [comment]
in v1.1.0 I've added support for testing Reminder registrations. Note that both reminders and timers won't be called automatically during testing. You should not see that crash anymore.

**Comment by sandersaares** [comment]
Awesome! Thanks for the fast action! I confirm that this appears to solve my problem!
