### ISSUE TITLE
'ServiceFabric.Mocks.MockStatefulServiceContextFactory' threw an exception.

### ISSUE THREAD

**Issue by felipecruz91** [loekd/ServiceFabric.Mocks#33]
Hi,

I am trying to do some very basic unit tests around my `SchedulerActor`  but I cannot get that working.

```
    private static SchedulerActor CreateActor(ActorId id)
    {
      Func<ActorService, ActorId, ActorBase> actorFactory = (service, actorId) => new SchedulerActor(service, id);
      var svc = MockActorServiceFactory.CreateActorServiceForActor<SchedulerActor>(actorFactory);
      var actor = svc.Activate(id);
      return actor;
    }

```

The **exception message**: 

```
System.TypeInitializationException : The type initializer for 'ServiceFabric.Mocks.MockStatefulServiceContextFactory' threw an exception.
  ----> System.TypeLoadException : Method 'ReportApplicationHealth' in type 'ServiceFabric.Mocks.MockCodePackageActivationContext' from assembly 'ServiceFabric.Mocks, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at ServiceFabric.Mocks.MockActorServiceFactory.CreateActorServiceForActor[TActor](Func`3 actorFactory, IActorStateProvider actorStateProvider, StatefulServiceContext context, ActorServiceSettings settings)
```

**Comment by loekd** [comment]
Which version of SF are you running? That version should match the version that the package is built for. (You can see the versions in the release notes.)

**Comment by felipecruz91** [comment]
I am using the `Microsoft.ServiceFabric` version 5.6.220. However, I cannot find that version in the release notes.

**Comment by loekd** [comment]
please use v2.2.0 of this package to see if that helps.

**Comment by felipecruz91** [comment]
I am afraid that using the version `2.2.0` of `ServiceFabric.Mocks` is throwing exactly the same exception. I would really like to get it working as I find very interesting your package. Do you have any other idea?

**Comment by loekd** [comment]
can you find out what the exact signature is of the overload of `ReportApplicationHealth`  it's looking for?
there are 2 implementations there
[1](https://github.com/loekd/ServiceFabric.Mocks/blob/5c480020dc2d87315f5589eccc9d74df1caded49/src/ServiceFabric.Mocks/MockCodePackageActivationContext.cs#L231)
[2](https://github.com/loekd/ServiceFabric.Mocks/blob/5c480020dc2d87315f5589eccc9d74df1caded49/src/ServiceFabric.Mocks/MockCodePackageActivationContext.cs#L246)
I'm wondering what implementation it's searching for.

**Comment by felipecruz91** [comment]
Disassembling the `ServiceFabric.Mocks v.2.2.0` code I can see that for the `MockCodePackageActivationContext.cs` file the **only** signature that appears is:

`public void ReportApplicationHealth(HealthInformation healthInformation)`.

This is the exception message:

`System.TypeInitializationException : The type initializer for 'ServiceFabric.Mocks.MockStatefulServiceContextFactory' threw an exception.
  ----> System.TypeLoadException : Method 'ReportApplicationHealth' in type 'ServiceFabric.Mocks.MockCodePackageActivationContext' from assembly 'ServiceFabric.Mocks, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at ServiceFabric.Mocks.MockActorServiceFactory.CreateActorServiceForActor[TActor](Func`3 actorFactory, IActorStateProvider actorStateProvider, StatefulServiceContext context, ActorServiceSettings settings)`

**Comment by loekd** [comment]
can you try using v2.2.2, in that version, [more ](https://github.com/loekd/ServiceFabric.Mocks/commit/836001fa8709aae5372d138988fb410917a78269#diff-926370f3a5e196b9a556674f2540a0df)overloads were added

**Comment by felipecruz91** [comment]
Great! That fixed that particular exception, however, it fails now in the line:

`var actor = svc.Activate(new ActorId(Guid.NewGuid()));`

Exception:

`System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.MissingMethodException : Constructor on type 'HeatLossCalcService.Scheduler.SchedulerActor' not found.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at ServiceFabric.Mocks.ActorServiceExtensions.Activate[TActor](ActorService actorService, ActorId actorId)`

**Comment by loekd** [comment]
Glad I could help. If you're good to go, please close the issue.
