### ISSUE TITLE
TimeoutException during IReliableDictionary.TryUpdateAsync

### ISSUE THREAD

**Issue by NArnott** [loekd/ServiceFabric.Mocks#61]
It seems to be a timing thing, and maybe more than one call is trying to access the same entry at the same time, but they are all wrapped in transactions so I don't see why this should happen:

System.TimeoutException: The operation has timed out.
   at ServiceFabric.Mocks.ReliableCollections.Lock`1.<Acquire>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ServiceFabric.Mocks.ReliableCollections.LockManager`2.<AcquireLock>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ServiceFabric.Mocks.ReliableCollections.TransactedConcurrentDictionary`2.<TryUpdateAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
**further stack trace redacted**

**Comment by NArnott** [comment]
A little more exploring and I think I found the issue. 

I make multiple passes on a given dictionary entry, each using a transaction. First pass adds an entry and commits, second pass reads it, and the third pass then tries to remove it. The removal is where the crash occurs.

The issue is that I don't explicitly call ITransaction.Abort() on the second pass when it decides to read and not do anything, but ITransaction.Dispose() is called. Based on https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-work-with-reliable-collections, calling Abort is not necessary if you call dispose. However, this bug remains unless I call Abort before disposing the transactions on my second pass. This should not be necessary, and it works fine when not using the mocks.

**Comment by NArnott** [comment]
Nevermind. I guess the initial pull of the record from the dictionary didn't include the transaction as an argument. Not sure why it only showed up in mocking (maybe it just hasn't happened in real life yet), but it's working with that change. Thanks for your mocks. It is very helpful.
